"use client";

import { useEffect, useState } from "react";
import { AccountPerformance } from "@/app/api/analytics/route";

import { Pillar } from "@/types";

const colors = [
  "var(--account-1)",
  "var(--account-2)",
  "var(--account-3)",
  "var(--account-4)",
  "var(--account-5)",
  "var(--account-6)",
  "var(--account-7)",
];

const pillarColors: Record<Pillar, string> = {
  capx: "var(--pillar-capx)",
  niche: "var(--pillar-niche)",
  personal: "var(--pillar-personal)",
};

export default function AnalyticsPage() {
  const [performances, setPerformances] = useState<AccountPerformance[]>([]);
  const [totals, setTotals] = useState({
    impressions: 0,
    likes: 0,
    replies: 0,
    clicks: 0,
    tweetsCount: 0,
    engagementRate: 0,
  });
  const [loading, setLoading] = useState(true);
  const [metricTab, setMetricTab] = useState<"clicks" | "impressions" | "engagement">("clicks");

  const fetchAnalytics = async () => {
    try {
      setLoading(true);
      const res = await fetch("/api/analytics");
      const data = await res.json();
      if (data.success) {
        setPerformances(data.performances);
        setTotals(data.totals);
      }
    } catch (err) {
      console.error("Failed to load analytics data:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAnalytics();
  }, []);

  if (loading) {
    return (
      <>
        <div className="page-header">
          <h1 className="page-title">Analytics</h1>
          <p className="page-subtitle">Performance insights per account, per pillar — what&apos;s driving Capx traffic?</p>
        </div>
        <div className="page-body">
          <div className="card skeleton" style={{ height: "400px" }} />
        </div>
      </>
    );
  }

  // Sort performance array depending on selected metric tab
  const sortedPerformances = [...performances].sort((a, b) => {
    if (metricTab === "clicks") return b.clicks - a.clicks;
    if (metricTab === "impressions") return b.impressions - a.impressions;
    return b.engagementRate - a.engagementRate;
  });

  const maxVal = Math.max(...performances.map((p) => {
    if (metricTab === "clicks") return p.clicks;
    if (metricTab === "impressions") return p.impressions;
    return p.engagementRate;
  }));

  const mockTopTweets = [
    { id: "t1", handle: "@persona1", text: "Autonomous business networks are the next paradigm. orchestrating multi-agents dynamically on-chain is lowkey the easiest way to launch. Capx is building this rail fr.", pillar: "capx", engagements: 42, clicks: 18 },
    { id: "t2", handle: "@persona5", text: "honestly spent 3 hours building custom agent playbooks today. coding up multi-step loops is lowkey addictive. who wants to check the code?", pillar: "niche", engagements: 29, clicks: 5 },
    { id: "t3", handle: "@persona3", text: "pixel just ate my printed checklist sheet. guess i'm running full auto mode for the remainder of this batch. literal definition of agent takeover.", pillar: "personal", engagements: 35, clicks: 0 },
  ];

  const handleCopyDigest = () => {
    const bestPerformer = [...performances].sort((a, b) => b.clicks - a.clicks)[0];
    const digestText = `# AutoX — Weekly Performance Digest
Generated on: ${new Date().toLocaleDateString()}

## Network Totals
- **Total Published Posts**: ${totals.tweetsCount}
- **Total Impressions/Views**: ${totals.impressions.toLocaleString()}
- **Capx Link Clicks**: ${totals.clicks}
- **Average Engagement Rate**: ${totals.engagementRate}%

## Top Performing Account
- **Persona**: ${bestPerformer ? `${bestPerformer.handle} (${bestPerformer.name})` : "N/A"}
- **Link Clicks Driven**: ${bestPerformer ? bestPerformer.clicks : 0}
- **Impressions**: ${bestPerformer ? bestPerformer.impressions.toLocaleString() : 0}

---
*Generated by AutoX Multi-Agent Persona Orchestrator*`;

    navigator.clipboard.writeText(digestText);
    alert("Weekly Markdown Digest copied to clipboard!");
  };

  return (
    <>
      {/* Page Header */}
      <div className="page-header" style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <div>
          <h1 className="page-title">Analytics</h1>
          <p className="page-subtitle">Performance insights per account, per pillar — what&apos;s driving Capx traffic?</p>
        </div>
        <button className="btn btn-secondary btn-sm" onClick={handleCopyDigest}>
          📋 Copy Weekly Digest
        </button>
      </div>

      {/* Body */}
      <div className="page-body">
        {/* Totals Summary Cards */}
        <div style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
          gap: "16px",
          marginBottom: "28px",
        }}>
          {/* Clicks */}
          <div className="stat-card animate-fade-in">
            <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "12px" }}>
              <div style={{
                width: "36px",
                height: "36px",
                borderRadius: "var(--radius-md)",
                background: "var(--accent-secondary-muted)",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}>
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="var(--accent-secondary)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
                  <polyline points="15 3 21 3 21 9" />
                  <line x1="10" y1="14" x2="21" y2="3" />
                </svg>
              </div>
            </div>
            <div className="stat-value">{totals.clicks}</div>
            <div className="stat-label">Capx Link Click-Throughs</div>
          </div>

          {/* Impressions */}
          <div className="stat-card animate-fade-in" style={{ animationDelay: "0.05s" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "12px" }}>
              <div style={{
                width: "36px",
                height: "36px",
                borderRadius: "var(--radius-md)",
                background: "rgba(79, 172, 254, 0.15)",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}>
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#4facfe" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
                  <line x1="9" y1="3" x2="9" y2="21" />
                  <line x1="15" y1="3" x2="15" y2="21" />
                </svg>
              </div>
            </div>
            <div className="stat-value">{totals.impressions.toLocaleString()}</div>
            <div className="stat-label">Total Impressions</div>
          </div>

          {/* Engagement */}
          <div className="stat-card animate-fade-in" style={{ animationDelay: "0.1s" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "12px" }}>
              <div style={{
                width: "36px",
                height: "36px",
                borderRadius: "var(--radius-md)",
                background: "rgba(240, 147, 251, 0.15)",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}>
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#f093fb" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M22 12h-4l-3 9L9 3l-3 9H2" />
                </svg>
              </div>
            </div>
            <div className="stat-value">{totals.engagementRate}%</div>
            <div className="stat-label">Average Engagement Rate</div>
          </div>

          {/* Sent Count */}
          <div className="stat-card animate-fade-in" style={{ animationDelay: "0.15s" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "12px" }}>
              <div style={{
                width: "36px",
                height: "36px",
                borderRadius: "var(--radius-md)",
                background: "var(--accent-primary-muted)",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}>
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="var(--accent-primary)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <polygon points="12 2 2 22 22 22" />
                </svg>
              </div>
            </div>
            <div className="stat-value">{totals.tweetsCount}</div>
            <div className="stat-label">Published Tweets Count</div>
          </div>
        </div>

        {/* Dynamic Metric Progress Feed */}
        <div style={{ display: "grid", gridTemplateColumns: "1fr 340px", gap: "24px", alignItems: "start" }}>
          
          {/* Main metric grid */}
          <div className="card" style={{ padding: "24px" }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px" }}>
              <h3 style={{ fontSize: "16px", fontWeight: 600, color: "var(--text-primary)" }}>
                Share of Traffic Contribution
              </h3>
              
              {/* Tab Selector */}
              <div style={{ display: "flex", background: "var(--bg-tertiary)", borderRadius: "var(--radius-md)", padding: "3px" }}>
                {[
                  { id: "clicks", label: "Clicks" },
                  { id: "impressions", label: "Impressions" },
                  { id: "engagement", label: "Engagement" },
                ].map((tab) => (
                  <button
                    key={tab.id}
                    onClick={() => setMetricTab(tab.id as any)}
                    className="btn btn-ghost btn-sm"
                    style={{
                      background: metricTab === tab.id ? "var(--bg-card)" : "transparent",
                      borderRadius: "var(--radius-sm)",
                      padding: "6px 12px",
                      color: metricTab === tab.id ? "var(--text-primary)" : "var(--text-secondary)",
                      fontSize: "12px",
                    }}
                  >
                    {tab.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Contribution Progress Bars */}
            <div style={{ display: "flex", flexDirection: "column", gap: "20px" }}>
              {sortedPerformances.map((perf, i) => {
                const color = perf.color || colors[i % colors.length];
                const activeVal = metricTab === "clicks" ? perf.clicks : metricTab === "impressions" ? perf.impressions : perf.engagementRate;
                const percent = maxVal > 0 ? Math.round((activeVal / maxVal) * 100) : 0;
                
                return (
                  <div key={perf.id} style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                      <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                        <div style={{ width: "8px", height: "8px", borderRadius: "50%", background: color }} />
                        <span style={{ fontSize: "13px", fontWeight: 600, color: "var(--text-primary)" }}>
                          {perf.handle}
                        </span>
                        <span style={{ fontSize: "12px", color: "var(--text-tertiary)" }}>
                          ({perf.name})
                        </span>
                      </div>
                      <span style={{ fontSize: "13px", fontWeight: 600, color: "var(--text-secondary)" }}>
                        {metricTab === "clicks"
                          ? `${perf.clicks} clicks`
                          : metricTab === "impressions"
                          ? `${perf.impressions.toLocaleString()} views`
                          : `${perf.engagementRate}%`}
                      </span>
                    </div>

                    <div style={{ height: "8px", background: "var(--bg-secondary)", borderRadius: "4px", overflow: "hidden" }}>
                      <div
                        style={{
                          width: `${percent}%`,
                          height: "100%",
                          background: `linear-gradient(90deg, ${color}cc, ${color})`,
                          borderRadius: "4px",
                          transition: "width 0.6s cubic-bezier(0.16, 1, 0.3, 1)",
                        }}
                      />
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Right column: top performing content */}
          <div style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
            <div className="card" style={{ padding: "20px" }}>
              <h3 style={{ fontSize: "15px", fontWeight: 600, color: "var(--text-primary)", marginBottom: "16px" }}>
                Top Performing Tweets (This Week)
              </h3>
              
              <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
                {mockTopTweets.map((t) => (
                  <div
                    key={t.id}
                    style={{
                      padding: "12px",
                      background: "var(--bg-secondary)",
                      borderRadius: "var(--radius-md)",
                      border: "1px solid var(--border-primary)",
                      display: "flex",
                      flexDirection: "column",
                      gap: "8px",
                    }}
                  >
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                      <span style={{ fontSize: "11px", fontWeight: 700, color: "var(--accent-primary)" }}>
                        {t.handle}
                      </span>
                      <span className={`badge`} style={{
                        background: `${pillarColors[t.pillar as Pillar]}15`,
                        color: pillarColors[t.pillar as Pillar],
                        fontSize: "9px",
                        textTransform: "uppercase",
                      }}>
                        {t.pillar}
                      </span>
                    </div>

                    <p style={{
                      fontSize: "11px",
                      color: "var(--text-secondary)",
                      lineHeight: "1.4",
                      margin: 0,
                    }}>
                      &ldquo;{t.text}&rdquo;
                    </p>

                    <div style={{ display: "flex", gap: "12px", borderTop: "1px solid var(--border-secondary)", paddingTop: "6px", marginTop: "2px" }}>
                      <span style={{ fontSize: "10px", color: "var(--text-tertiary)" }}>
                        📈 {t.engagements} engagements
                      </span>
                      {t.clicks > 0 && (
                        <span style={{ fontSize: "10px", color: "var(--accent-secondary)" }}>
                          🔗 {t.clicks} clicks
                        </span>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

        </div>
      </div>
    </>
  );
}
